/**
 * DemoRunner — runs the complete AgentVault story behind a single endpoint.
 *
 * The narrative (5 acts):
 *   1. approved payment
 *   2. escrow creation
 *   3. escrow release
 *   4. prompt-injection attack — blocked
 *   5. overspend attack — blocked
 *
 * Verdicts are produced deterministically by the policy firewall (the proven
 * mock scenario engine), so the demo always tells the same, correct story with
 * zero external dependencies. Each act is persisted to the EventStore.
 *
 * Alongside the verdicts we surface the agent's LLM outputs (what the agent
 * *proposed*) for the three agent-driven acts. These are best-effort: real
 * model output when Ollama is configured, otherwise a deterministic fallback —
 * so the endpoint never fails just because the LLM is unavailable.
 */

import { runAllScenarios } from "../agent/scenarios.ts";
import { AgentRunner, type PaymentRequest } from "../agent/AgentRunner.ts";
import { ADDRESSES, AMOUNTS, REASONS } from "../agent/constants.ts";
import { log } from "../lib/logger.ts";
import { tryBuildOnChainRunner } from "./OnChainDemoRunner.ts";
import type { ScenarioResult } from "../types/scenario.ts";

// --- Dependency contract --------------------------------------------------

export interface PaymentAgent {
  generatePaymentRequest(task?: string): Promise<PaymentRequest>;
  generatePromptInjectionRequest(task?: string): Promise<PaymentRequest>;
  generateOverspendRequest(task?: string): Promise<PaymentRequest>;
}

export interface DemoRunnerDeps {
  /** Agent for LLM outputs. Defaults to AgentRunner from env, if configured. */
  agent?: PaymentAgent;
}

// --- Response types -------------------------------------------------------

export type DemoScenario = "safe_payment" | "prompt_injection" | "overspend";

export interface LlmOutput {
  scenario: DemoScenario;
  /** "ollama" = generated by the model; "fallback" = deterministic stand-in. */
  source: "ollama" | "fallback";
  request: PaymentRequest;
}

export interface DemoSummary {
  approvedPayments: number;
  blockedPayments: number;
  escrowOperations: number;
  totalEvents: number;
}

export interface DemoRunResponse {
  summary: DemoSummary;
  llmOutputs: LlmOutput[];
  events: ScenarioResult[];
}

// --- Deterministic LLM fallbacks ------------------------------------------

const FALLBACK: Record<DemoScenario, PaymentRequest> = {
  safe_payment: {
    to: ADDRESSES.apiProvider,
    amount: AMOUNTS.safePayment,
    actionType: "PAYMENT",
    reason: REASONS.safePayment,
  },
  prompt_injection: {
    to: ADDRESSES.badActor,
    amount: AMOUNTS.promptInjection,
    actionType: "TRANSFER",
    reason: REASONS.promptInjection,
  },
  overspend: {
    to: ADDRESSES.apiProvider,
    amount: AMOUNTS.overspend,
    actionType: "PAYMENT",
    reason: REASONS.overspend,
  },
};

/** Build an AgentRunner from env, or undefined if Ollama isn't configured. */
function tryBuildAgent(): PaymentAgent | undefined {
  try {
    return AgentRunner.fromEnv({ silent: true });
  } catch {
    return undefined;
  }
}

// --- Runner ---------------------------------------------------------------

export class DemoRunner {
  private readonly agent?: PaymentAgent;

  constructor(deps: DemoRunnerDeps = {}) {
    this.agent = deps.agent ?? tryBuildAgent();
  }

  /** Run the full story and return all events + all LLM outputs. */
  async fullRun(): Promise<DemoRunResponse> {
    // LLM proposals (real Ollama) run in parallel with the verdict source.
    const llmPromise = this.collectLlmOutputs();

    // Prefer the REAL on-chain runner when a chain is configured. Each act is a
    // live Monad transaction with a real txHash. Fall back to the deterministic
    // mock engine only when no chain/keys are available (MOCK_CHAIN=true).
    const onchain = tryBuildOnChainRunner();
    if (onchain) {
      try {
        const [llmOutputs, { summary, events }] = await Promise.all([llmPromise, onchain.run()]);
        log.info("demo.onchain_run", { totalEvents: events.length });
        return { summary, llmOutputs, events };
      } catch (err) {
        log.error("demo.onchain_failed", { error: err instanceof Error ? err.message : String(err) });
        throw err;
      }
    }

    const llmOutputs = await llmPromise;
    const events = runAllScenarios({ reset: true });
    return { summary: summarize(events), llmOutputs, events };
  }

  /** Best-effort LLM outputs for the three agent-driven acts. */
  private async collectLlmOutputs(): Promise<LlmOutput[]> {
    const specs: Array<{ scenario: DemoScenario; gen: () => Promise<PaymentRequest> }> = [
      { scenario: "safe_payment", gen: () => this.agent!.generatePaymentRequest() },
      { scenario: "prompt_injection", gen: () => this.agent!.generatePromptInjectionRequest() },
      { scenario: "overspend", gen: () => this.agent!.generateOverspendRequest() },
    ];

    // Run the three agent calls concurrently (≈3× faster than sequential) while
    // preserving spec order. Each independently falls back if its call fails.
    return Promise.all(
      specs.map(async ({ scenario, gen }): Promise<LlmOutput> => {
        if (this.agent) {
          try {
            return { scenario, source: "ollama", request: await gen() };
          } catch (err) {
            log.warn("demo.llm_fallback", {
              scenario,
              error: err instanceof Error ? err.message : String(err),
            });
          }
        }
        return { scenario, source: "fallback", request: FALLBACK[scenario] };
      }),
    );
  }
}

function summarize(events: ScenarioResult[]): DemoSummary {
  let approvedPayments = 0;
  let blockedPayments = 0;
  let escrowOperations = 0;
  for (const e of events) {
    if (e.status === "APPROVED") approvedPayments++;
    else if (e.status === "BLOCKED") blockedPayments++;
    else if (e.status === "ESCROW_CREATED" || e.status === "ESCROW_RELEASED") escrowOperations++;
  }
  return { approvedPayments, blockedPayments, escrowOperations, totalEvents: events.length };
}
